### ISSUE TITLE
Open questions regarding retargeting 

### ISSUE THREAD

**Issue by hybridherbst** [takahirox/EXT_skin_humanoid#18]
I think there may be a misunderstanding to what animation retargeting means in practice: it does not mean applying the same transformations to another node hierarchy. It means applying the same normalized motion to another rig specifying motion ranges.

Recommend reading about Unity's Avatar definitions for humanoid characters, how they're set up, what they store, and how retargeting works there!

I understand for a "simple" extension the goal may be to not allow actual retargeting but just allow applying the same transformations to another hierarchy, but then it should be explicit.

**Comment by takahirox** [comment]
Thanks for the comment.

OK, the term "retargeting" doesn't sound like applying the same animation to models that have the same or similar structured skeleton in general.

Perhaps I should have used "remap" or anything else. Actual "retargeting" is out of scope. I will update to clarify.

**Comment by hybridherbst** [comment]
Just as an example, here's Unity's Avatar setup window, where one basically defines the range of motion for a character, which is the base for retargeting humanoid animations to it:
![image](https://user-images.githubusercontent.com/2693840/215222595-3acf88e7-fd78-464c-8cbf-bbdef9d903e1.png)

**Comment by hybridherbst** [comment]
Humanoid clips in Unity then animate in that motion range, so it can be retargeted. I don't think it's hugely more complicated to store avatar definitions and avatar animation clips separately (and we plan to do that for Needle Engine in the future), would be great to align on a format for that.

![image](https://user-images.githubusercontent.com/2693840/215225308-c9a9d239-6f09-41f8-805d-6670a54e6002.png)

**Comment by takahirox** [comment]
What is the motion range exactly and how does it work?

**Comment by mrxz** [comment]
Even just applying the transforms from a source skeleton to a target skeleton relative to a known rest pose constitutes retargeting, albeit the most basic form. So I don't think it's necessarily wrong to use that term in this context, though I do agree it should be clear what is and isn't covered/supported by this extension.

The tricky thing with retargetting is that there are many ways to fix up the resulting animation. Limiting joint rotations to avoid self-collision is also only part of the whole solution. To have proper contact points with props or the ground you often see a form of IK being used as well.

I don't know how these motion ranges are used in Unity exactly, but I imagine that limiting joint movement is useful even outside of animation retargeting (e.g. procedural animations, IK, rag doll physics). So I think it's worth considering to keep the scope of this extension to describing the humanoid skeleton and make the actual retarget logic non-normative. Any joint constraints can then be defined using a separate extension, which doesn't have to be limited to humanoid skeleton/joints.

**Comment by takahirox** [comment]
> Any joint constraints can then be defined using a separate extension

Yes, this is my first option in my mind.

**Comment by hybridherbst** [comment]
I don't quite agree here; if you have a character with low arm range, you want to see the normalized motion on it, not some full motion but then clamped to the range of that character, two very different results.

Regarding IK, indeed Unity allows adding IK on top of humanoid rigs for more directly specifying hand and feet positions; this could certainly be a separate extension.

**Comment by mrxz** [comment]
I might be missing something, but it feels highly dependant on the animation whether normalized motion makes sense. Clipping the motion looks quite bad, so I can see how normalized motion would yield better looking results. But wouldn't it mess with many movements incorrectly? For example, applying an animation of a character looking perfectly left, when applied to an "owl-like" character with a larger neck motion range, would be looking _over_ its shoulder. Or an animation on a character that can't cross his arms in front of him. Pointing straight forward would be the maximum motion, so when applied to other characters, they would cross their arms.

That being said, an extension for motion range based retargetting that works hand-in-hand with this extension sounds like the best of both worlds. There are many animation sources where motion range information of the source skeleton is simply not present (e.g. Mixamo, motion capture), so I don't think it would be wise to require it for this extension.
