### ISSUE TITLE
Are all bones required?

### ISSUE THREAD

**Issue by vpenades** [takahirox/EXT_skin_humanoid#7]
Question:  when you define a new skeleton humanoid, it is required to define all the bones?

Obviously, if you define LeftWrist, you must also define LeftElbow and all other bones up to the root.

My concern is with the hands, there's lots of joints there, and maybe a particular mesh or target model has less bones.

Also, what about the face?   eyes? chin?

**Comment by takahirox** [comment]
> Question: when you define a new skeleton humanoid, it is required to define all the bones?

No. They are optional and some of them can be omitted in an asset. I think it's the same as the VRM spec. I will add clarification about it in the spec.

> Also, what about the face? eyes? chin?

@robertlong has opened an issue #8 about it.
